### PR TITLE
Change the tag sys

### PR DESCRIPTION
**Pull request by Witnull**

### CODE REVIEW

**Review by JakeClark38a — APPROVED** [review]
You can add tag but can't delete tag? Just default tag (which has same name as group) aren't delete-able and editable. Other tag can edit to another group (which means all tasks marked this tag will change to new group location), delete (all tasks marked this tag will change to default tag) and edit.

**Comment by Witnull** [comment]
> You can add tag but can't delete tag?  yep, maybe that option can be used later :)))

**Comment by JakeClark38a** [comment]
Yeah, so continue your work. I'll try to add this function to this app.

**Comment by Witnull** [comment]
> Yeah, so continue your work. I'll try to add this function to this app.

ok

**Pull request merged**
